// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/user.proto

package user

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for User service

func NewUserEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for User service

type UserService interface {
	// 发送短信验证码
	SendSms(ctx context.Context, in *SmsReq, opts ...client.CallOption) (*SmsRsp, error)
	// 注册
	Register(ctx context.Context, in *RegReq, opts ...client.CallOption) (*ReqRsp, error)
	// 登录
	Login(ctx context.Context, in *LoginReq, opts ...client.CallOption) (*LoginRsp, error)
	// 获取用户信息
	GetUserInfo(ctx context.Context, in *UserInfoReq, opts ...client.CallOption) (*UserInfoRsp, error)
	// 更新用户名
	UpdateUserName(ctx context.Context, in *UserNameReq, opts ...client.CallOption) (*UserNameRsp, error)
	// 用户实名认证
	UserAuthPost(ctx context.Context, in *UserAuthReq, opts ...client.CallOption) (*UserAuthRsp, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) SendSms(ctx context.Context, in *SmsReq, opts ...client.CallOption) (*SmsRsp, error) {
	req := c.c.NewRequest(c.name, "User.SendSms", in)
	out := new(SmsRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Register(ctx context.Context, in *RegReq, opts ...client.CallOption) (*ReqRsp, error) {
	req := c.c.NewRequest(c.name, "User.Register", in)
	out := new(ReqRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Login(ctx context.Context, in *LoginReq, opts ...client.CallOption) (*LoginRsp, error) {
	req := c.c.NewRequest(c.name, "User.Login", in)
	out := new(LoginRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetUserInfo(ctx context.Context, in *UserInfoReq, opts ...client.CallOption) (*UserInfoRsp, error) {
	req := c.c.NewRequest(c.name, "User.GetUserInfo", in)
	out := new(UserInfoRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) UpdateUserName(ctx context.Context, in *UserNameReq, opts ...client.CallOption) (*UserNameRsp, error) {
	req := c.c.NewRequest(c.name, "User.UpdateUserName", in)
	out := new(UserNameRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) UserAuthPost(ctx context.Context, in *UserAuthReq, opts ...client.CallOption) (*UserAuthRsp, error) {
	req := c.c.NewRequest(c.name, "User.UserAuthPost", in)
	out := new(UserAuthRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserHandler interface {
	// 发送短信验证码
	SendSms(context.Context, *SmsReq, *SmsRsp) error
	// 注册
	Register(context.Context, *RegReq, *ReqRsp) error
	// 登录
	Login(context.Context, *LoginReq, *LoginRsp) error
	// 获取用户信息
	GetUserInfo(context.Context, *UserInfoReq, *UserInfoRsp) error
	// 更新用户名
	UpdateUserName(context.Context, *UserNameReq, *UserNameRsp) error
	// 用户实名认证
	UserAuthPost(context.Context, *UserAuthReq, *UserAuthRsp) error
}

func RegisterUserHandler(s server.Server, hdlr UserHandler, opts ...server.HandlerOption) error {
	type user interface {
		SendSms(ctx context.Context, in *SmsReq, out *SmsRsp) error
		Register(ctx context.Context, in *RegReq, out *ReqRsp) error
		Login(ctx context.Context, in *LoginReq, out *LoginRsp) error
		GetUserInfo(ctx context.Context, in *UserInfoReq, out *UserInfoRsp) error
		UpdateUserName(ctx context.Context, in *UserNameReq, out *UserNameRsp) error
		UserAuthPost(ctx context.Context, in *UserAuthReq, out *UserAuthRsp) error
	}
	type User struct {
		user
	}
	h := &userHandler{hdlr}
	return s.Handle(s.NewHandler(&User{h}, opts...))
}

type userHandler struct {
	UserHandler
}

func (h *userHandler) SendSms(ctx context.Context, in *SmsReq, out *SmsRsp) error {
	return h.UserHandler.SendSms(ctx, in, out)
}

func (h *userHandler) Register(ctx context.Context, in *RegReq, out *ReqRsp) error {
	return h.UserHandler.Register(ctx, in, out)
}

func (h *userHandler) Login(ctx context.Context, in *LoginReq, out *LoginRsp) error {
	return h.UserHandler.Login(ctx, in, out)
}

func (h *userHandler) GetUserInfo(ctx context.Context, in *UserInfoReq, out *UserInfoRsp) error {
	return h.UserHandler.GetUserInfo(ctx, in, out)
}

func (h *userHandler) UpdateUserName(ctx context.Context, in *UserNameReq, out *UserNameRsp) error {
	return h.UserHandler.UpdateUserName(ctx, in, out)
}

func (h *userHandler) UserAuthPost(ctx context.Context, in *UserAuthReq, out *UserAuthRsp) error {
	return h.UserHandler.UserAuthPost(ctx, in, out)
}
