// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/hellomicro.proto

package hellomicro

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Hellomicro service

func NewHellomicroEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Hellomicro service

type HellomicroService interface {
	Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error)
}

type hellomicroService struct {
	c    client.Client
	name string
}

func NewHellomicroService(name string, c client.Client) HellomicroService {
	return &hellomicroService{
		c:    c,
		name: name,
	}
}

func (c *hellomicroService) Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error) {
	req := c.c.NewRequest(c.name, "Hellomicro.Call", in)
	out := new(CallResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Hellomicro service

type HellomicroHandler interface {
	Call(context.Context, *CallRequest, *CallResponse) error
}

func RegisterHellomicroHandler(s server.Server, hdlr HellomicroHandler, opts ...server.HandlerOption) error {
	type hellomicro interface {
		Call(ctx context.Context, in *CallRequest, out *CallResponse) error
	}
	type Hellomicro struct {
		hellomicro
	}
	h := &hellomicroHandler{hdlr}
	return s.Handle(s.NewHandler(&Hellomicro{h}, opts...))
}

type hellomicroHandler struct {
	HellomicroHandler
}

func (h *hellomicroHandler) Call(ctx context.Context, in *CallRequest, out *CallResponse) error {
	return h.HellomicroHandler.Call(ctx, in, out)
}
